# Generated by Django 2.0.1 on 2018-03-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(default='unknown', max_length=20)),
                ('registration_number', models.CharField(default='unknown', max_length=10, unique=True)),
                ('number_of_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20, unique=True)),
                ('country', models.CharField(default='unknown', max_length=20)),
                ('time_zone', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='unknown', max_length=20, unique=True)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ONHOLD', 'On hold'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('TRAVELLED', 'Travelled')], max_length=15)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(default='unknown', max_length=20)),
                ('dep_datetime', models.DateTimeField()),
                ('arr_datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('price', models.FloatField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Aircraft')),
                ('dep_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='airline.Airport')),
                ('dest_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='airline.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(default='unknown', max_length=20, unique=True)),
                ('amount', models.FloatField()),
                ('is_paid', models.BooleanField()),
                ('electronic_stamp', models.CharField(default='unknown', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='unknown', max_length=20)),
                ('surname', models.CharField(default='unknown', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='unknown', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('website', models.URLField()),
                ('account_number', models.CharField(default='unknown', max_length=30)),
                ('username', models.CharField(default='unknown', max_length=20)),
                ('password', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='airline.Passenger'),
        ),
    ]
